// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _JMD_LCM_Image_Type_h
#define _JMD_LCM_Image_Type_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _JMD_LCM_Image_Type JMD_LCM_Image_Type;
struct _JMD_LCM_Image_Type
{
    int64_t    Timestamp;
    int32_t    DataSize;
    int16_t    Height;
    int16_t    Width;
    int16_t    Stride;
    int8_t     Channels;
    int8_t     PixelSize;
    uint8_t    *Data;
};

/**
 * Create a deep copy of a JMD_LCM_Image_Type.
 * When no longer needed, destroy it with JMD_LCM_Image_Type_destroy()
 */
JMD_LCM_Image_Type* JMD_LCM_Image_Type_copy(const JMD_LCM_Image_Type* to_copy);

/**
 * Destroy an instance of JMD_LCM_Image_Type created by JMD_LCM_Image_Type_copy()
 */
void JMD_LCM_Image_Type_destroy(JMD_LCM_Image_Type* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _JMD_LCM_Image_Type_subscription_t JMD_LCM_Image_Type_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * JMD_LCM_Image_Type is received.
 */
typedef void(*JMD_LCM_Image_Type_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const JMD_LCM_Image_Type *msg, void *userdata);

/**
 * Publish a message of type JMD_LCM_Image_Type using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int JMD_LCM_Image_Type_publish(lcm_t *lcm, const char *channel, const JMD_LCM_Image_Type *msg);

/**
 * Subscribe to messages of type JMD_LCM_Image_Type using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
JMD_LCM_Image_Type_subscription_t* JMD_LCM_Image_Type_subscribe(lcm_t *lcm, const char *channel, JMD_LCM_Image_Type_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by JMD_LCM_Image_Type_subscribe()
 */
int JMD_LCM_Image_Type_unsubscribe(lcm_t *lcm, JMD_LCM_Image_Type_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int JMD_LCM_Image_Type_subscription_set_queue_capacity(JMD_LCM_Image_Type_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type JMD_LCM_Image_Type into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to JMD_LCM_Image_Type_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int JMD_LCM_Image_Type_encode(void *buf, int offset, int maxlen, const JMD_LCM_Image_Type *p);

/**
 * Decode a message of type JMD_LCM_Image_Type from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with JMD_LCM_Image_Type_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int JMD_LCM_Image_Type_decode(const void *buf, int offset, int maxlen, JMD_LCM_Image_Type *msg);

/**
 * Release resources allocated by JMD_LCM_Image_Type_decode()
 * @return 0
 */
int JMD_LCM_Image_Type_decode_cleanup(JMD_LCM_Image_Type *p);

/**
 * Check how many bytes are required to encode a message of type JMD_LCM_Image_Type
 */
int JMD_LCM_Image_Type_encoded_size(const JMD_LCM_Image_Type *p);

// LCM support functions. Users should not call these
int64_t __JMD_LCM_Image_Type_get_hash(void);
uint64_t __JMD_LCM_Image_Type_hash_recursive(const __lcm_hash_ptr *p);
int     __JMD_LCM_Image_Type_encode_array(void *buf, int offset, int maxlen, const JMD_LCM_Image_Type *p, int elements);
int     __JMD_LCM_Image_Type_decode_array(const void *buf, int offset, int maxlen, JMD_LCM_Image_Type *p, int elements);
int     __JMD_LCM_Image_Type_decode_array_cleanup(JMD_LCM_Image_Type *p, int elements);
int     __JMD_LCM_Image_Type_encoded_array_size(const JMD_LCM_Image_Type *p, int elements);
int     __JMD_LCM_Image_Type_clone_array(const JMD_LCM_Image_Type *p, JMD_LCM_Image_Type *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
